sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t arghageek/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arghageek/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-132416110445'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
